DROP TABLE BitacoraVentas;
DROP TABLE Factura;
DROP TABLE Bitacora;
DROP TABLE Cajero;
DROP TABLE Usuario;
DROP TABLE Productos;
DROP TABLE TipoUsuario;
DROP TABLE TipoArea;

-- Tabla TipoArea
CREATE TABLE admin.TipoArea (
  Codigo VARCHAR2(9) NOT NULL,
  Descripcion VARCHAR2(30) NOT NULL,
  PRIMARY KEY (Codigo)
);

-- Tabla TipoUsuario
CREATE TABLE admin.TipoUsuario (
  Codigo VARCHAR2(9) NOT NULL,
  Descripcion VARCHAR2(30) NOT NULL,
  PRIMARY KEY (Codigo)
);

-- Tabla Productos
CREATE TABLE admin.Productos (
	PLU NUMBER(5),
  EAN VARCHAR2(13) NOT NULL,
  Descripcion VARCHAR2(45) NOT NULL,
	Area VARCHAR2(9) NOT NULL,
  Precio NUMBER NOT NULL,
  Peso NUMBER NOT NULL,
	Cantidad NUMBER,
  PRIMARY KEY (EAN),
	FOREIGN KEY (Area) REFERENCES TipoArea (Codigo),
	UNIQUE (PLU)
);

-- Tabla Usuario
CREATE TABLE admin.Usuario (
  Codigo VARCHAR2(9) NOT NULL,
  Nombre VARCHAR2(75) NOT NULL,
  Password VARCHAR2(16) NOT NULL,
  Area VARCHAR2(9) NOT NULL,
  Rol VARCHAR2(9) NOT NULL,
  PRIMARY KEY (Codigo),
  FOREIGN KEY (Area) REFERENCES TipoArea (Codigo),
	FOREIGN KEY (Rol) REFERENCES TipoUsuario (Codigo)
);

-- Tabla Cajero
CREATE TABLE admin.Cajero (
	Usuario VARCHAR2(9) NOT NULL,
  Caja NUMBER NOT NULL,
  PRIMARY KEY (Usuario),
	FOREIGN KEY (Usuario) REFERENCES Usuario (Codigo)
);

-- Tabla Bitacora
CREATE TABLE admin.Bitacora (
  Codigo VARCHAR2(20) NOT NULL,
  OperacionRealizada VARCHAR2(100) NOT NULL,
	Usuario VARCHAR2(50) NOT NULL,
  Fecha VARCHAR2(50) NOT NULL,
  Hora VARCHAR2(50) NOT NULL,
	Tabla VARCHAR2(20) NOT NULL,
  PRIMARY KEY (Codigo)
);

-- Tabla Factura
CREATE TABLE admin.Factura (
  Codigo NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
	Producto VARCHAR2(13) NOT NULL,
	Cantidad NUMBER NOT NULL, 
  Subtotal NUMBER NOT NULL,
  Total NUMBER NOT NULL,
  Cajero VARCHAR2(9) NOT NULL,
  Fecha VARCHAR2(10) NOT NULL,
	Hora VARCHAR2(5) NOT NULL, 
  PRIMARY KEY (Codigo),
	FOREIGN KEY (Producto) REFERENCES Productos (EAN),
  FOREIGN KEY (Cajero) REFERENCES Cajero (Usuario)
);

-- Tabla BitacoraVentas
CREATE TABLE admin.BitacoraVentas (
  Bitacora VARCHAR2(50) NOT NULL,
  Factura NUMBER NOT NULL,
  PRIMARY KEY (Bitacora),
	FOREIGN KEY (Factura) REFERENCES Factura (Codigo)
);

COMMIT;